apiVersion: v1
kind: Secret
metadata:
  name: proxmox-creds
  namespace: crossplane-system
type: Opaque
stringData:
  TF_VAR_proxmox_endpoint: https://192.168.0.66:8006/api2/json
  TF_VAR_proxmox_username: root@pam
  TF_VAR_proxmox_token: root@pam!auto_vm=b6b05fae-cddc-4749-be2a-5517b61cd36a
  TF_VAR_datacenter_user: root
  TF_VAR_datacenter_pass: Pve1LPAFqu4r
  
