apiVersion: dnacloud.home/v1alpha1
kind: cloudInfra
metadata:
  name: test
  namespace: test
spec:
  region: us-east-1
  resources:
    s3:
      enabled: false
      bucketName: random-bucket-101010101
    ec2:
      enabled: false
      instanceName: random-instance-10101
      imageID: ami-020cba7c55df1f615
      instanceType: t3.micro
    db:
      enabled: true
      dbName: mydb
      username: aaa
      password: aaaa
      instanceClass: db.t3.micro
      dbType: postgres
      #engineVersion: "15"

    vpc:
      name: example-vpc
      enabled: true
      cidr: "10.0.0.0/24"
    
    subnet:
      enabled: false
      name: example-subnet

